# Generated by Django 6.0.8 on 2026-09-26 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_userprofile_social_enabled_webhook_userfollow'),
        ('exercises', '0041_alter_historicaltranslation_description_and_more'),
        ('manager', '0030_workoutsession_is_public_routinesharetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['user', 'date'], name='manager_wor_user_id_1d398a_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(
                fields=['routine', 'iteration'], name='manager_wor_routine_436fb4_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(
                fields=['user', 'is_public', 'datetime_start'],
                name='manager_wor_user_id_c5b53e_idx',
            ),
        ),
    ]
